#!/usr/bin/env python3
"""Package `cargo ledger build` outputs into a sideload bundle consumed by `ledger_installer.py`.

The input is a cargo target directory (local `target/` or the CI `app_binaries` artifact) laid out as
`<device>/release/<elf>` next to the `<elf>.apdu` install script and `<elf>.sha256` application hash
that cargo-ledger generates. The bundle holds one `<device>.apdu` per device plus a `manifest.json`
describing each of them, so the installer never has to parse an ELF or rebuild load parameters.
"""

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

try:
    from elftools.common.exceptions import ELFError
    from elftools.elf.elffile import ELFFile
except ModuleNotFoundError as e:
    raise SystemExit("Missing dependency 'pyelftools'. Install it with: python3 -m pip install pyelftools") from e

MANIFEST_NAME = "manifest.json"
MANIFEST_SCHEMA = 1
METADATA_SECTIONS = ("target", "target_id", "app_name", "app_version", "api_level", "sdk_version")
# The Nano X OS rejects apps loaded outside Ledger Live.
SIDELOAD_UNSUPPORTED_TARGETS = {"nanox"}


def read_elf_metadata(elf_path: Path) -> dict[str, str] | None:
    """Return the `ledger.*` metadata sections of a Ledger app ELF, or None if the file is not one."""
    with elf_path.open("rb") as f:
        try:
            elf = ELFFile(f)
        except ELFError:
            return None
        metadata = {}
        for name in METADATA_SECTIONS:
            section = elf.get_section_by_name(f"ledger.{name}")
            if section is None:
                return None
            metadata[name] = section.data().decode("utf-8").strip()
        return metadata


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def find_apps(target_dir: Path) -> list[tuple[Path, dict[str, str]]]:
    apps = []
    for elf_path in sorted(target_dir.glob("*/release/*")):
        if not elf_path.is_file() or elf_path.suffix:
            continue
        metadata = read_elf_metadata(elf_path)
        if metadata is not None:
            apps.append((elf_path, metadata))
    return apps


def make_bundle(target_dir: Path, out_dir: Path, source: dict[str, str | bool]) -> dict:
    apps = find_apps(target_dir)
    if not apps:
        raise SystemExit(f"No Ledger app ELF found under {target_dir}/<device>/release/")

    names = {(m["app_name"], m["app_version"]) for _, m in apps}
    if len(names) != 1:
        raise SystemExit(f"Refusing to mix different apps or versions in one bundle: {sorted(names)}")
    app_name, app_version = names.pop()

    out_dir.mkdir(parents=True, exist_ok=True)
    entries: list[dict[str, str]] = []
    for elf_path, metadata in apps:
        device = metadata["target"]
        if device in SIDELOAD_UNSUPPORTED_TARGETS:
            print(f"  - {device:<10} skipped: sideloading is not supported on this device")
            continue
        apdu_src = elf_path.with_suffix(".apdu")
        hash_src = elf_path.with_suffix(".sha256")
        for required in (apdu_src, hash_src):
            if not required.is_file():
                raise SystemExit(f"Missing {required} (generated by `cargo ledger build`)")

        apdu_name = f"{device}.apdu"
        shutil.copyfile(apdu_src, out_dir / apdu_name)
        entries.append(
            {
                "device": device,
                "target_id": metadata["target_id"],
                "api_level": metadata["api_level"],
                "sdk_version": metadata["sdk_version"],
                "app_hash": hash_src.read_text().strip(),
                "apdu_file": apdu_name,
                "apdu_sha256": sha256_file(out_dir / apdu_name),
            }
        )
        print(f"  + {device:<10} target_id={metadata['target_id']} api_level={metadata['api_level']}")

    if not entries:
        raise SystemExit("No sideloadable device in the build outputs")
    manifest = {
        "schema": MANIFEST_SCHEMA,
        "app_name": app_name,
        "app_version": app_version,
        "source": source,
        "apps": entries,
    }
    (out_dir / MANIFEST_NAME).write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("target_dir", type=Path, help="Cargo target directory containing <device>/release/<elf>")
    parser.add_argument("out_dir", type=Path, help="Output bundle directory")
    parser.add_argument("--source-ref", default="local", help="Branch, pull request or tag the app was built from")
    parser.add_argument("--commit", default="", help="Commit SHA the app was built from")
    parser.add_argument("--official", action="store_true", help="The bundle is a tagged release, not a development build")
    args = parser.parse_args()

    source: dict[str, str | bool] = {"ref": args.source_ref, "commit": args.commit, "official": args.official}
    manifest = make_bundle(args.target_dir, args.out_dir, source)
    print(f"Bundle for '{manifest['app_name']}' {manifest['app_version']} written to {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
